title: Algorithm E-Book
description: A multi-language algorithm reference guide.
theme: jekyll-theme-minimal
baseurl: "/algorithms"
plugins:
  - jekyll-relative-links
exclude:
  - node_modules
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true